### ISSUE TITLE
ReferenceError: g is not defined

### ISSUE THREAD

**Issue by HighTide** [kieler/elkjs#127] opened 2021-03-24 15:22 UTC
I get the following error:

```core.js:6185 ERROR Error: Uncaught (in promise): ReferenceError: g is not defined
ReferenceError: g is not defined
    at Emd (elk-worker.min.js:5037)
    at Iqd (elk-worker.min.js:5685)
    at h.dispatch (elk-worker.min.js:5984)
    at h.saveDispatch (elk-worker.min.js:5984)
    at elk-worker.min.js:5985
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41264)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at timer (zone-evergreen.js:2552)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41264)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at invokeTask (zone-evergreen.js:484)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at timer (zone-evergreen.js:2552)
```
This issue is caused by the elk-worker.min.js file. the elk-worker.min.js:formatted has the following code:

```js
function Emd(a, b, c) {
    var d, e, f, h, i, j;
    d = smd(a, (e = (ddd(),
    f = new Bkd,
    f),
    !!c && zkd(e, c),
    e), b);
    kgd(d, Ald(b, Xoe));
    Hmd(b, d);
    Cmd(b, d);
    Imd(b, d);
    g = null;
    h = b;
    i = xld(h, 'ports');
    j = new ind(a,d);
    emd(j.a, j.b, i);
    Dmd(a, b, d);
    ymd(a, b, d);
    return d
}
```

It uses the var g, however, g is not being defined as var. It can be fixed manually by adding g to the var declarations, like this.

```js
function Emd(a, b, c) {
    var d, e, f, g, h, i, j;
    d = smd(a, (e = (ddd(),
    f = new Bkd,
    f),
    !!c && zkd(e, c),
    e), b);
    kgd(d, Ald(b, Xoe));
    Hmd(b, d);
    Cmd(b, d);
    Imd(b, d);
    g = null;
    h = b;
    i = xld(h, 'ports');
    j = new ind(a,d);
    emd(j.a, j.b, i);
    Dmd(a, b, d);
    ymd(a, b, d);
    return d
}
```

I would normally create a pull request, however as far as I can tell the elk-worker gets generated from the GWT code and I have no idea how this issue can be solved.

**Comment by uruuru** [comment] 2021-03-24 17:28
Could this be related to #96?

You are correct in that the code is fully generated.

**Comment by HighTide** [comment] 2021-03-24 17:42
Yes, it looks like it's the same problem. I'm also using it inside an angular project so strict mode is on.

**Comment by uruuru** [comment] 2021-04-07 19:59
As explained in #96, I'm not aware of a "fix" other than excluding elkjs from being handled in strict mode. I'm open for suggestions though.

**Comment by amcdnl** [comment] 2021-06-07 12:21
Removing strict mode will resolve the issue - depending on what build system you use it might add it automatically. For example, rollup does but u can turn this off like:

```
module.exports = [
  {
    input: './src/Embed/Embed.tsx',
    output: [
      {
        file: pkg.browser,
        sourcemap: true,
        format: 'umd',
        name: 'flow',
        strict: false
      }
    ],
```

**Comment by Qix-** [comment] 2021-06-13 20:29
Browser are strict by default these days, and there's no way to run in non-strict mode. Why that affects execution times is very strange, though.

At any rate, there's a missing variable in the declared `var a, b, c, d, etc` clause above in this function (and a few other functions). Adding those variables manually fixes the issue and 100% will not affect runtime. **Thus, this seems to be a bug in whatever generates the javascript.** Clearly they're pre-declaring variables (which isn't required in non-strict mode) but are missing several (which causes bugs within strict mode).

This is preventing us from using Elk without vendoring it in and manually adjusting things. I'll have to fork and see if I can't get it building myself :/

**Comment by Qix-** [comment] 2021-06-13 22:37
I wrote a patcher for the build process - the repository is at my https://github.com/qix-/elkjs fork. This fixes the broken GWT output (maybe not completely - you'll need to add to `worker-patch.js` in the root if it doesn't).

I also removed all of the extra layout algorithms as an additional, singular commit. This cut down the output size by almost a megabyte. If you need anything other than `layered`, you can `git revert bc9f97e19e91f6cde67f2ad988bfa8884aa24ffd` and re-build.

If you intend to publish on your own, revert the HEAD commit as well and make whatever changes you need to the package.json yourself.

Hope that helps anyone that comes across this bug that nobody (not even the GWT team) wants to fit.

**Comment by uruuru** [comment] 2021-06-16 19:57
> Thus, this seems to be a bug in whatever generates the javascript.

I agree. If somebody finds the root cause, is able to address it within GWT and triggers a new release of GWT, I'd the first to create a new elkjs release. 

Injecting the missing variables as a patch after the actual build seems to be a reasonable workaround to me. Would you be open to create a PR with just this change? 

Regarding removing the other layouters: they may be "superfluous" to you but not in general. #6 also mentions the size differences. If somebody has a suggestion for a low-effort or automated process to publish variants (for instance, `layered` and `all` as a start), I'm happy to integrate it.

**Comment by Qix-** [comment] 2021-06-16 21:28
> Regarding removing the other layouters: they may be "superfluous" to you but not in general.

Yes of course, I didn't mean to suggest they were superfluous _in general_, just to my use-case - hence why I gave instructions on how to revert that change if someone wanted to use my version.

**Comment by uruuru** [comment] 2021-06-20 18:51
I just realized that a better place to add the missing variables is likely below here
https://github.com/kieler/elkjs/blob/874bd4b29f900788a97e5aa3e208dc74613b52af/src/java/org/eclipse/elk/js/linker/NodeJsModuleLinker.java#L46

**Comment by uruuru** [comment] 2021-10-31 09:34
Should be fixed in 0.7.3-dev.

**Closed by uruuru** 2021-10-31 09:34 UTC

**Comment by KonradLinkowski** [comment] 2022-01-14 16:13
@uruuru do you plan to release 0.7.3 as a full version?

**Comment by uruuru** [comment] 2022-02-26 20:01
There are plans for a new elk release within the next month. A subsequent elkjs release would include the fixes.

**Comment by luanlucho** [comment] 2022-06-12 15:56
Any solutions yet?

**Comment by soerendomroes** [comment] 2022-06-13 08:09
elkjs 0.8.1 is released (but not yet tagged as latest), have you tried whether this fixes the issue?

**Comment by livwvil** [comment] 2022-06-16 14:23
elkjs 0.8.1 fixes this issue for me

**Comment by jyc** [comment] 2022-06-20 23:47
Thanks for fixing this uruuru! If you enable donations or sponsorships on GitHub people might be interested!

**Comment by tunesmith** [comment] 2022-08-28 01:23
Just pointing out that `npm install elkjs` still installs 0.7.1, but changing the version number in package.json does find 0.8.1 successfully.

**Comment by waynelwz** [comment] 2022-08-29 10:02
I have building by vite, elkjs 0.8.1 is not work for me, I resolved it tricky by 

EDIT:
just write this on App.js or App.tsx:
window.g = null;
window.i = null;
elkjs: 0.7.1

**Comment by Qix-** [comment] 2022-08-29 10:24
The dist-tag is `next`, by the way. `latest` is still tagged under the 0.7 version.

Maintainers, mind pushing this straight to `latest`? It'll cut down on the confused responses here.

Everyone else, use `npm install elkjs@next` for now, if you want.
