### ISSUE TITLE
Module not found: Can't resolve 'web-worker' in in '/elkjs/lib'

### ISSUE THREAD

**Issue by talkhanz** [kieler/elkjs#143] opened 2021-08-06 11:50 UTC
Hey,

Just installed this using npm and my react application shows this error up?

The suggested methods in other similar issues didn't do the trick..

Any help would be appreciated,

Best

**Comment by uruuru** [comment] 2021-08-07 07:20
See #142, #141.

**Comment by talkhanz** [comment] 2021-08-07 07:43
Hey @uruuru  thank you for reaching but I am not sure how to use the suggestion provided in #141

**Comment by uruuru** [comment] 2021-10-31 09:06
I'm not familiar with react myself, so I cannot add any further details. 

I'll close this issue as duplicate of the others.

**Closed by uruuru** 2021-10-31 09:06 UTC
